// <auto-generated />
using System;
using DataScraping;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataScraping.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240427160717_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("DataScraping.DataInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CUI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodPostal")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtendedData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Localitate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MFINANCE")
                        .HasColumnType("TEXT");

                    b.Property<string>("NrOfBranches")
                        .HasColumnType("TEXT");

                    b.Property<string>("Owners")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SediuSocial")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialCapital")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<string>("Web")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CUI");

                    b.ToTable("DataInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
